const surveyConstant = {
    // Account
    SHOW_USERNAME: "SHOW_USERNAME",
    CREATE_NEW_SURVEY: "CREATE_NEW_SURVEY",
    DELETE_SURVEY: "DELETE_SURVEY",
    SET_SHOW_SIGNIN_FORM: "SET_SHOW_SIGNIN_FORM",
    // Survey
    SHOW_SURVEY_LIST: "SHOW_SURVEY_LIST",
    CHANGE_ACTIVE_SURVEY: "CHANGE_ACTIVE_SURVEY",
    SHOW_EDIT_SURVEY: "SHOW_EDIT_SURVEY",
    CHANGE_VIEW_SURVEY: "CHANGE_VIEW_SURVEY",
    SET_SHOW_MODAL_URL: "SET_SHOW_MODAL_URL",
    SHOW_SURVEY_LINK: "SHOW_SURVEY_LINK",
    SHOW_RESULT: "SHOW_RESULT"
}
export default surveyConstant
